version: '3'

services:
  shutfs:
    build:
      context: .
      dockerfile: docker/Dev.dockerfile
    image: zikoel/shutfs:development
    command: ['npm', 'run', 'dev:start']
    volumes:
      - './nodemon.json:/app/nodemon.json'
      - './package.json:/app/package.json'
      - './tsconfig_master.json:/app/tsconfig_master.json'
      - './tsconfig.json:/app/server/tsconfig.json'
      - './:/app/server'
    tmpfs:
      - /data
    ports:
      - '5000:5000'
    env_file: .env

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
