name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Setup node'
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
      working-directory: server
    - run: yarn build
      working-directory: server
    - name: Upload server dist
      uses: actions/upload-artifact@v1
      with:
        name: server-dist
        path: server/dist
  build-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Setup node'
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
      working-directory: client
    - run: yarn build
      working-directory: client
    - name: Upload client build
      uses: actions/upload-artifact@v1
      with:
        name: client-build
        path: client/build
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [build-server, build-client]
    steps:
      - name: Download server dist
        uses: actions/download-artifact@v1
        with:
          name: server-dist
          path: server/dist
      - name: Download client build
        uses: actions/download-artifact@v1
        with:
          name: client-build
          path: client/build
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: zikoel/shutfs/shutfs
          tag_with_ref: true
          dockerfile: server/docker/Prod.dockerfile

